from langchain_core.messages import AIMessage
import asyncio
from langchain_core.agents import AgentFinish
from langsmith.schemas import Feedback
from typing import Optional
from langgraph.constants import END
from langgraph.constants import START
from langchain_core.messages import content
from pydantic import BaseModel, Field
from typing import Literal
from langgraph.graph import StateGraph
from app.core.config import settings
from langchain.chat_models import init_chat_model
from typing import Annotated, TypedDict
from langchain.messages import HumanMessage, SystemMessage, AnyMessage

from langgraph.graph import add_messages


class AgentState(TypedDict):
    messages : Annotated[list[AnyMessage], add_messages]
    draft : Optional[str]
    feedback : Optional[str]
    evaluation : Optional[Literal["passed", "failed"]]
    iterations : int



llm = init_chat_model(model = "gpt-4o-mini", model_provider="openai", api_key = settings.OPENAI_API_KEY)


class CriticStructure(BaseModel):
    feedback : str = Field(description="Critic ki di hui galtiyan/suggestions yahan save hongi")
    evaluation : Literal["passed", "failed"] = Field(description="will be either failed or passed based on the feedback")

critic_llm = llm.with_structured_output(schema=CriticStructure)




async def actor_node(state : AgentState) -> AgentState:
    messages = state["messages"]
    iteration = state["iterations"]
    feedback = state["feedback"]
    draft = state["draft"]
   
    system_prompt = SystemMessage(content=f"""
You are an Expert Technical Documentation Writer.
Your job is to write clear, professional, and comprehensive system specifications or API documentation in clean Markdown format based on the user's request.

CRITICAL INSTRUCTIONS:
1. Use standard Markdown structuring (H1, H2, code blocks for JSON/Python, bullet points).
2. For APIs, always include: Overview, Endpoint URL/Method, Request Payload, Response Payload, and Error Codes.
3. Keep the tone objective and highly technical.
4. DO NOT add conversational filler (e.g., "Here is your documentation"). Output ONLY the Markdown content.

FEEDBACK HANDLING:
If you receive feedback from the Senior Reviewer, you MUST address EVERY single point of criticism. Rewrite the draft to fix the issues mentioned in the feedback.
Here is your previously written draft : {draft}.
Here is the feedback for the draft from the Senior Reviewer : {feedback}
""")

    response = await llm.ainvoke([system_prompt] + messages)

    return {
        "draft" : response.content,
        "iterations" : iteration + 1
    }




async def critic_node(state : AgentState) -> AgentState:
    messages = state["messages"]
    draft = state["draft"]
    
    system_prompt = SystemMessage(content=f"""
You are a highly strict Senior Staff Engineer reviewing technical documentation.
Your job is to review the drafted documentation provided to you and ensure it meets production-grade standards.
User messaging content : {messages}

REVIEW CRITERIA:
1. Formatting: Is it written in valid, clean Markdown?
2. Completeness: Does it include request/response payloads and practical examples?
3. Error Handling: Are potential error codes (400, 401, 404, 500) and their explanations included?
4. Clarity: Is the logic and flow easy for a junior developer to understand?

INSTRUCTIONS:
- If the documentation is flawless and meets ALL criteria, approve it.
- If it is missing ANYTHING (especially examples or error codes), reject it and provide a specific, bulleted list of what needs to be fixed.
- Do not be polite. Be direct, clear, and actionable.
""")


    human_message = HumanMessage(content = f"""
here is the draft generated by the actor node you have to evaluate it : {draft}
    """)
    
    response : CriticStructure = await critic_llm.ainvoke([system_prompt, human_message])


    return{
        "feedback" : response.feedback,
        "evaluation" : response.evaluation
    }



def routing_after_critic_node(state : AgentState) -> Literal["failed", "passed"]:
    evaluation = state["evaluation"]
    iteration = state["iterations"]
    if evaluation == "passed":
        return "passed"

    elif iteration >= 3 :
        return "passed"
    else:
        return "failed"



async def finalize_node(state: AgentState) -> dict:
    final_draft = state["draft"] # Kitchen se perfect dish uthayi
    
    return {
        "messages": [AIMessage(content=final_draft)] # Table pe serve kar di!
    }


graph = StateGraph(state_schema=AgentState)
graph.add_node("actor_node", actor_node)
graph.add_node("critic_node", critic_node)
graph.add_node("finalize_node", finalize_node)


graph.add_edge(START, "actor_node")
graph.add_edge("actor_node", "critic_node")

graph.add_conditional_edges("critic_node", routing_after_critic_node, {"failed" : "actor_node", "passed" : "finalize_node"})
graph.add_edge("finalize_node", END)


workflow = graph.compile()



async def run_workflow():
    initial_state : AgentState = {
        "messages" : [HumanMessage(content="I have created a database querying agent for a business app for a foreign client")],
        "draft" : None,
        "feedback" : None,
        "evaluation" : None,
        "iterations" : 0
    }

    final_state : AgentState = await workflow.ainvoke(initial_state)

    # print(final_state)

    # print("\n\n")

    # print(final_state["draft"])
    # print("\n\n")

    print(final_state["messages"])
    print("\n\n")
    # print(final_state["feedback"])




asyncio.run(run_workflow())